updated the images path in the blog content
debezium/debezium.github.io pull request #520
Opened 2020-11-04 06:28 UTC by indraraj

- Updated the images asset path in the blog content.

2020-11-04 16:48 UTC, mdrillin requested changes
The path changes indicated can be left as-is

2020-11-04 16:48 UTC, mdrillin commented on _posts/2020-09-15-debezium-auto-create-topics.adoc
> +    <img src="/assets/assets/images/new_pipes.jpg" class="responsive-image" alt="Create new topics / pipes">
This path looks ok as-is

2020-11-04 16:48 UTC, mdrillin commented on _posts/2020-10-08-debezium-community-stories-with-renato-mefi.adoc
> +<img src="/assets/assets/images/renatomefi.jpg" style="max-width:50%;" class="responsive-image">
The 3 image paths in this file look ok as-is

2020-11-05 05:35 UTC, indraraj commented
Thanks for pointing, I have updated the pr.

2020-11-05 05:37 UTC, indraraj commented on _posts/2020-09-15-debezium-auto-create-topics.adoc
> +    <img src="/assets/assets/images/new_pipes.jpg" class="responsive-image" alt="Create new topics / pipes">
reverted

2020-11-05 14:18 UTC, mdrillin approved these changes
looks good, thanks for updating!

2020-11-05 14:18 UTC, merged